-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 11:28:54 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema OIDTREE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OIDTREE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OIDTREE` DEFAULT CHARACTER SET latin1 ;
USE `OIDTREE` ;

-- -----------------------------------------------------
-- Table `OIDTREE`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OIDTREE`.`agent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(50) NOT NULL,
  `port` INT NOT NULL,
  `version` INT NOT NULL,
  `secname` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OIDTREE`.`agentv3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OIDTREE`.`agentv3` (
  `id` INT NOT NULL,
  `auth_proto` VARCHAR(45) NULL,
  `auth_pwd` VARCHAR(45) NULL,
  `priv_proto` VARCHAR(45) NULL,
  `priv_pwd` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `OIDTREE`.`agent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OIDTREE`.`oidnode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OIDTREE`.`oidnode` (
  `oid` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NULL,
  `lft` INT NOT NULL,
  `rht` INT NULL,
  PRIMARY KEY (`lft`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
